version: '2.3'
services:
   jekyll-server:
      image: jekyll_image:{{cookiecutter.username.lower().replace(' ', '_')}}-{{cookiecutter.project_name.lower().replace(' ', '_')}}
      container_name: jekyll_container-{{cookiecutter.username.lower().replace(' ', '_')}}-{{cookiecutter.project_name.lower().replace(' ', '_')}}
      build: docker
      ports:
         - "0.0.0.0:8081:8888"
      volumes:
         - $PWD:/srv/jekyll
      ipc: host
      command: jekyll build
      stdin_open: true
      tty: true



